Airbnb Price Prediction/AirBnB price prediction.ipynb, Spotify Recommendation/Spotify Playlist Recommender.ipynb
Fixes issue #83 
1) Added relative path in read_csv() function
2) Changed test-size from 0.25 to 0.2 and random_state from 101 to 42
3) df_train.info()
4) df_train.describe()
=> Fix issues 83

Airbnb Price Prediction/AirBnB price prediction.ipynb, Spotify Recommendation/Spotify Playlist Recommender.ipynb
Fixes #75 by checking for null vales in the dataset and then by handling missing values in the dataset.
1) CHECKED MISSING VALUES 
2) HANDLING MISSING VALUES
(a) By dropping null values
(b) By replacing null values
=> Handling Missing Values

IPL Score Prediction/IPL Score Prediction.ipynb
Fixes issue #12 
Initially:
After change:
=> Add: Changed data type of date column from string to datetime

Startup Profit Prediction/Startup Profit Prediction.ipynb
**### issue 1 was solved and modified**
null values were checked
if found they were replaced by the mean of the existing values in that column. 
image also attached above for reference
=> solved issue #1 under Startup Profile Prediction

Spotify Recommendation/Spotify Playlist Recommender.ipynb
#Fixes : #69 #70  
Created a bar plot showing the top 10 most popular tracks based on frequency in playlists and the top 10 most popular tracks based on frequency in playlists.
=> Solved issue no. 69 and 70

IPL Score Prediction/IPL Score Prediction.ipynb
=> Issue #11 Removing the first five overs in every match

Startup Profit Prediction/Startup Profit Prediction.ipynb
Hi, Issue #3 has been resolved, please look forward to it.
Changes made :
Imported the required libraries :
Solved the issue - Split the Testing & Training sets i 80:20 Ratio :
Thank you :)
=> ISSUE #3 - Split data into train and test (80:20)

Budget Tracking Tool/BudgetTracker.py
Fixes issue #58 
Screenshot of test cases
=> Add: (Issue #58) Validation logic for amount 

Sudoku Solver Game/SudokuSolver.py
I made an attempt in resolving the issue of getting valid integers as input for the grid. 
picture for reference also i have attached.
please let me know if a change or a difference approach is required!
=> #48Ensure all inputs are valid integers between 1 and 6 

Startup Profit Prediction/Startup Profit Prediction.ipynb
testing model on test dataset, the output of y_pred is an array containing the predicted values
=> issue#5 startupPrediction testing model

Sudoku Solver Game/SudokuSolver.py
informing the user if the puzzle cannot be solved, through a messagebox.
=> issue#49 FIXED sudokuSolver informing for unsolvable puzzles

Credit Card Fraud Detection/Credit Card Fraud Detection.ipynb
=> Fixes issue #39

Emotion Detection/Emotion Detection.ipynb
=> Fixes issue #30

IPL Score Prediction/IPL Score Prediction.ipynb
Solved issue no. #14 IPL Score Prediction: Add Feature Scaling to Numerical Columns
=> Solved issue no. #14

Sudoku Solver Game/SudokuSolver.py
displaying the time taken to solve puzzle. created a new variable (start_time), before the if-block, to record the time at the start of the solving process.
=> issue#50 sudokuSolver time taken to solve puzzle

IPL Score Prediction/IPL Score Prediction.ipynb
Hi, Issue #13 has been resolved, please look forward to it.
Changes made :
1) Defined a function to remove outliers.
2) Applied the function to all the numerical columns.
Thank you :)
=> ISSUE #13 - Handle Outliers in Data Preprocessing

Startup Profit Prediction/Startup Profit Prediction.ipynb
Hi, Issue #9 has been resolved, please look forward to it.
Changes made :
Import the required library & written the code for Plotting/Data Visualisation : 
Thank you :)
=> ISSUE #9 -  Plot Predicted vs Actual Values

Credit Card Fraud Detection/Credit Card Fraud Detection.ipynb
Added Standard Scalar function for 'Amount' column explicitly
(A) Applying Standard Normalisation for ' Amount ' Column
(B)  Using fit_transform() to apply on the dataset
=> Added StandardScalar function for Amount Column

Credit Card Fraud Detection/Credit Card Fraud Detection.ipynb
Added the Function to visualize Confusion Matrix for model evaluation
=> Fix issue 40

Credit Card Fraud Detection/Credit Card Fraud Detection.ipynb
Implemented using Random Forest
(A) 
(B) Trained the model using Random Forest
(C) Made predictions from trained model
=> Fix issue 45

IPL Score Prediction/IPL Score Prediction.ipynb
Hi, Issue #16 has been resolved, please look forward to it.
Changes made :
1) Applied Random Forest Regression Model.
2) Evaluated the respective model.
Thank you :)
=> ISSUE #16 - Apply Random Forest Regression Model

IPL Score Prediction/IPL Score Prediction.ipynb
Reverts GDG-IGDTUW/AI-ML-1#151
=> Revert "ISSUE #16 - Apply Random Forest Regression Model"

Startup Profit Prediction/Startup Profit Prediction.ipynb
Hi, Issue #10 has been resolved, please look forward to it.
Changes made :
Imported the required libraries & displayed the Classification Report : 
Thank you :)
=> ISSUE #10 - Use classification_report to compute evaluation

IPL Score Prediction/IPL Score Prediction.ipynb
Hi, Issue #16 has been resolved, please look forward to it.
Changes made :
1) Applied Random Forest Regression Model.
2) Evaluated the respective model.
Thank you :)
=> (New PR) ISSUE #16 - Apply Random Forest Regression Model

Airbnb Price Prediction/AirBnB price prediction.ipynb
Issue 86 resolved: evaluated the performance of random forest regression model and linear regression model. 
Calculated Mean Squared Error (MSE), Mean Absolute Error (MAE), and R-squared (R²) values for the models and compared the two models.
@PJ40200 @ISaumya1011 Kindly review
=> Issue 86 resolved: Evaluated model's performace

Airbnb Price Prediction/AirBnB price prediction.ipynb
testing the model on an instance; comparing the actual & predicted value
@PJ40200 @ISaumya1011
=> issue#85 airbnbPricePrediction testing on an instance

Spotify Recommendation/Spotify Playlist Recommender.ipynb
i answered the assign task Assigned [#71](https://github.com/GDG-IGDTUW/AI-ML-1/issues/71) to [@Deepanjali01](https://github.com/Deepanjali01).
@Shanvi2005  kindly review it
=> Spotify Recommendation: Create a visualization showing the number of unique artists in each playlist. (Issue #71)

Budget Tracking Tool/BudgetTracker.py, budget_data.csv
-added checks on the range of the index entered by the user
-drives the user back to menu if index not valid
-the functions of update and delete transactions return back if index not valid though checks have already been made in the menu section
=> #Issue 61 - Validate the index provided by the user

Airbnb Price Prediction/AirBnB price prediction.ipynb
=> Issue #87 Hyperparameter Tuning in Airbnb project

Sudoku Solver Game/SudokuSolver.py
=> issue #56 Resolved Manya

Budget Tracking Tool/BudgetTracker.py
=> Issue 62 Automatically add the current date and time when a transaction is recorded BudgetTracker.py

Budget Tracking Tool/BudgetTracker.py
=> Issue #66 Allow users to generate a summary of transactions within a specific date range. BudgetTracker.py

Budget Tracking Tool/BudgetTracker.py
=> #59 Clear Screen Function Budget Tracker

Credit Card Fraud Detection/Credit Card Fraud Detection.ipynb
=> Issue #47 Credit card fraud detection
